# Generated by Django 5.2.1 on 2025-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0002_broadcastmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_speaker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Организатор'), ('speaker', 'Выступающий'), ('listener', 'Слушатель')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
