# Generated by Django 5.2.1 on 2025-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0003_remove_customuser_is_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
