# Generated by Django 5.2.1 on 2025-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0005_customuser_full_name_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления'),
        ),
    ]
